contas/urls.py
from django.conf.urls import patterns, url

urlpatterns = patterns('',
    url(r'^entrar/$', 'django.contrib.auth.views.login', {'template_name': 'contas/login.html'}, name='login'),
    url(r'^sair/$', 'django.contrib.auth.views.logout', {'next_page': 'noticias:index'}, name='logout'),
    url(r'^editar-senha/$', 'contas.views.edit_password', name='edit_password'),
)

core/urls.py
from django.conf.urls import patterns, url

urlpatterns = patterns('core.views',
    url(r'^index/$', 'base', name='index'),


)

leds/urls.py
from django.conf.urls import patterns, include, url

urlpatterns = patterns('leds.views',
    url(r'^$', 'ver_dados', name='leds'),
    
)

membros/urls.py
from django.conf.urls import patterns, url

urlpatterns = patterns('membros.views',
    url(r'^associados/$', 'show_associados', name='associados'),
    url(r'^associados/(?P<slug>[\w_-]+)/$', 'perfil', name='perfil'),
    url(r'^associados-submit/$', 'update_perfil', name='update_perfil'),
    url(r'^parceiros/$', 'show_parceiros', name='parceiros')

)

relatorio/urls.py
from django.conf.urls import patterns, include, url

urlpatterns = patterns('relatorio.views',
    url(r'^ata/$','relatorio', name='escrever-ata'),
    url(r'^listar_atas/$','relatorio_lista', name='listar_atas'),
    url(r'^listar_atas/(?P<pk>\d+)/$', 'ver_ata', name='ver_ata'),
)

site_leds/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = patterns('',
    url(r'^$', include('noticias.urls', namespace='noticias')),
    url(r'^conta/', include('contas.urls', namespace='contas')),
    url(r'^documentos-tecnicos/', include('doctecnicos.urls', namespace='doctecnicos')),
    url(r'^quem-somos/', include('membros.urls', namespace='membros')),
    # url(r'^$', include('noticias.urls', namespace='home')),
    url(r'^noticias/', include('noticias.urls', namespace='noticias')),
    url(r'^projetos/', include('projetos.urls', namespace='projetos')),
    url(r'^publicacoes/', include('publicacoes.urls', namespace='publicacoes')),
    url(r'^relatorio/', include('relatorio.urls', namespace='relatorio')),
    url(r'^quem-somos/', include('leds.urls', namespace='quemSomos')),
    url(r'^core/', include('core.urls', namespace='core')),#apagar depois

    # chamado no template base para exibir o perfil do associado ao clicar sobre o seu nome
    url(r'^quem-somos/associados/(?P<slug>[\w_-]+)/$', 'membros.views.perfil', name='perfil'),

    url(r'^redactor/', include('redactor.urls')),

    url(r'^admin/', include(admin.site.urls)),
)

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/models.py
from django.db import models

# Create your models here.

core/views.py
from django.shortcuts import render_to_response


def base(request):
    return render_to_response('base.html')

core/templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="pt-br">
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="shortcut icon" href="/media/imagem/customLogo2.png">
        <title>LEDS - Laborátorio de Sistemas Embarcados e Distribuidos</title>
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.2/jquery.min.js"></script>
        <script src="{% static 'bootstrap-3.3.2/js/jquery-1.11.2.js' %}"></script>
        <link href="{% static 'bootstrap-3.3.2/css/bootstrap.css' %}" rel="stylesheet">
        <script src="{% static 'bootstrap-3.3.2/js/bootstrap.js' %}"></script>
        <link href="{% static 'projeto/css/responsive.css' %}" rel="stylesheet">
        <link href="{% static 'bootstrap-3.3.2/css/prettyPhoto.css' %}" rel="stylesheet">
        <link href="{% static 'bootstrap-3.3.2/css/animate.min.css' %}" rel="stylesheet">

{#        <script src="{% static 'pt_pt.js' %}"></script>#}
{#        <script type="text/javascript">#}

        <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
        <meta name="description" content="">
        <meta name="author" content="">
    </head>

    <body class="padding-menu">
    <!-- NAVBAR
    ================================================== -->
    <nav class="navbar navbar-default navbar-fixed-top">
        <div class="container">
            <div class="col-md-2 col-lg-2 col-xs-4 col-sm-3">
                <a href="{% url 'noticias:index' %}">
                <img data-holder-rendered="true" src="/media/imagem/customLogo2.png" class="featurette-image img-responsive"
                     data-src="holder.js/500x500/auto" alt="100x80"></a>
            </div>

            <div class="navbar-header">
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                </button>

                <a class="navbar-brand" href="{% url 'noticias:index' %}">Home</a>

            </div>
            <div id="navbar" class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">LEDS <span class="caret"></span></a>
                        <ul class="dropdown-menu" role="menu">
                            <li><a href="{% url 'projetos:index' %}">Projetos</a></li>
                            <li><a href="{% url 'publicacoes:publicacoes' %}">Publicações</a></li>
                            <li><a href="{% url 'doctecnicos:documentos-tecnicos' %}">Documentos Técnicos</a></li>
                        </ul>
                    </li>
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Quem Somos<span class="caret"></span></a>
                        <ul class="dropdown-menu" role="menu">
                            <li><a href="{% url 'membros:associados' %}">Associados</a></li>
                            <li><a href="{% url 'membros:parceiros' %}">Parceiros</a></li>
                            <li><a href="{% url 'quemSomos:leds' %}">O Laboratório</a></li>
                        </ul>
                    </li>
                    {% if user.is_authenticated %}
                        <li class="dropdown">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Ata das Reuniões<span class="caret"></span></a>
                            <ul class="dropdown-menu" role="menu">
                                <li><a href="{% url 'relatorio:escrever-ata' %}">Nova Ata</a></li>
                                <li><a href="{% url 'relatorio:listar_atas' %}">Ver Atas</a></li>
                            </ul>
                        </li>
                    {% endif %}
                </ul>
                <ul class="nav navbar-nav navbar-right">
                    {% if user.is_authenticated %}
                        {% if user.sexo_member == 1 %}
                            <p class="navbar-t"><a id="link" href="{% url 'membros.views.perfil' user.slug  %}"> Bem vinda, {{ user }}
                        {% else %}
                            <p class="navbar-t"><a id="link" href="{% url 'membros.views.perfil' user.slug  %}"> Bem vindo, {{ user }}
                        {% endif %}
                        <img class="img-circle"
                        {% if user.profile_image %}
                            src="{{ user.profile_image.url }}"
                        {% elif user.sexo_member == 1 %}
                            src="/media/imagem/user-f.svg"
                        {% else %}
                            src="/media/imagem/user-m.svg"
                        {% endif %} alt="Generic placeholder image" style="width: 40px; height: 40px;"></a></p>
                        <li class="dropdown" style="margin-left: -20px;">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false"><span class="caret"></span></a>
                            <ul class="dropdown-menu" role="menu">
                                <li><a href="{% url 'contas:edit_password' %}">Editar Senha</a></li>
                            </ul>
                        </li>
                        <li class="active"><a href="{% url 'contas:logout' %}">Sair <span class="glyphicon glyphicon-log-out" aria-hidden="true">
                            <span class="sr-only">(current)</span></span></a></li>
                    {% else %}
                        <li class="active"><a href="{% url 'contas:login' %}">Login <span class="glyphicon glyphicon-log-in" aria-hidden="true">
                            <span class="sr-only">(current)</span></span></a></li>
                    {% endif %}
                </ul>
            </div><!--/.nav-collapse -->
        </div>
    </nav>
    <br><br>

    {% block conteudo %}{% endblock %}

    <br><br><br>
    <footer class="footer-main navbar-bottom footer">
        <div class="container">
            <div class="row">
                <p class="text-muted">Instituto Federal de Educação, Ciência e Tecnologia do Ceará - campus Crato (CNPJ: 10.744.098/0010-36)</p>
                <p class="text-muted">Rod. CE 292, Km 15, Gisélia Pinheiro - Crato - Ceará. CEP: 63115-500 | Fone: (88) 3586-8100</p>
            </div>
        </div>
    </footer>


    <!-- Include all compiled plugins (below), or include individual files as needed -->


  </body>
</html>