core/urls.py
from django.conf.urls import patterns, url

urlpatterns = patterns('core.views',
    url(r'^index/$', 'base', name='index'),


)

publicacoes/urls.py
from django.conf.urls import patterns, url

urlpatterns = patterns('publicacoes.views',
    url(r'^$', 'publicacoes', name='publicacoes'),
    url(r'^submeter-publicacoes/$', 'submeter_publicacao', name='submit-publicacoes'),
)

site_leds/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = patterns('',
    url(r'^$', include('noticias.urls', namespace='noticias')),
    url(r'^conta/', include('contas.urls', namespace='contas')),
    url(r'^documentos-tecnicos/', include('doctecnicos.urls', namespace='doctecnicos')),
    url(r'^quem-somos/', include('membros.urls', namespace='membros')),
    # url(r'^$', include('noticias.urls', namespace='home')),
    url(r'^noticias/', include('noticias.urls', namespace='noticias')),
    url(r'^projetos/', include('projetos.urls', namespace='projetos')),
    url(r'^publicacoes/', include('publicacoes.urls', namespace='publicacoes')),
    url(r'^relatorio/', include('relatorio.urls', namespace='relatorio')),
    url(r'^quem-somos/', include('leds.urls', namespace='quemSomos')),
    url(r'^core/', include('core.urls', namespace='core')),#apagar depois

    # chamado no template base para exibir o perfil do associado ao clicar sobre o seu nome
    url(r'^quem-somos/associados/(?P<slug>[\w_-]+)/$', 'membros.views.perfil', name='perfil'),

    url(r'^redactor/', include('redactor.urls')),

    url(r'^admin/', include(admin.site.urls)),
)

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

publicacoes/models.py
from django.db import models
from membros.models import Associados


class Publicacoes(models.Model):
    TIPO_PUBLICACOES_CHOICES = ((0, 'TCC'), (1, 'Periodicos'), (2, 'Anais de Congresso'))
    TIPO_ARTIGO_CHOICES = ((0, 'Artigos Completos'), (1, 'Resumo'), (2, 'Relatorios de Conclução'))
    ANO_CHOICES = ((2015, '2015'), (2014, '2014'), (2013, '2013'), (2012, '2012'), (2011, '2011'), (2010, '2010'))

    titulo = models.CharField('Titulo da Publicação', max_length=100)
    tipo_publicacao = models.IntegerField('Tipo de Publicação', choices=TIPO_PUBLICACOES_CHOICES, default=2, blank=True)
    tipo_artigo = models.IntegerField('Tipo de Artigo', choices=TIPO_ARTIGO_CHOICES, default=2, blank=True)
    nome_evento = models.CharField('Nome do Evento', max_length=100, blank=True)
    local_evento = models.CharField('Local do evento', max_length=100, blank=True)
    ano = models.IntegerField('Data da Publicação', choices=ANO_CHOICES, blank=True)
    arquivo = models.FileField('Arquivo', upload_to='media/pdf/%Y/%m/%d')
    autor_principal = models.ForeignKey(Associados, verbose_name='Autor Principal', related_name='autor_principal')
    autor_secundario = models.ManyToManyField(Associados, verbose_name='Co-autores', related_name='co-autor', blank=True)

    def get_year(self):
        return self.ano

    class Meta:
        verbose_name = 'Publicacao'
        verbose_name_plural = 'Publicações'
        ordering = ['-ano']

publicacoes/forms.py
from django import forms
from membros.models import Associados


class PublicacoesForm(forms.Form):
    TIPO_PUBLICACOES_CHOICES = ((0, 'TCC'), (1, 'Periodicos'), (2, 'Anais de Congresso'))
    TIPO_ARTIGO_CHOICES = ((0, 'Artigos Completos'), (1, 'Resumo'), (2, 'Relatorios de Conclução'))
    ANO_CHOICES = ((2015, '2015'), (2014, '2014'), (2013, '2013'), (2012, '2012'), (2011, '2011'), (2010, '2010'))

    titulo = forms.CharField(label='Titulo da Publicação', max_length=100,
                             widget=forms.TextInput(attrs={'class': 'form-control'}))
    tipo_publicacao = forms.ChoiceField(label='Tipo de Publicação', choices=TIPO_PUBLICACOES_CHOICES,
                                        widget=forms.Select(attrs={'class': 'form-control'}))
    tipo_artigo = forms.ChoiceField(label='Tipo de Artigo', choices=TIPO_ARTIGO_CHOICES,
                                    widget=forms.Select(attrs={'class': 'form-control'}))
    nome_evento = forms.CharField(label='Nome do Evento', max_length=100,
                                  widget=forms.TextInput(attrs={'class': 'form-control'}), required=False)
    local_evento = forms.CharField(label='Local do Evento', max_length=100,
                                  widget=forms.TextInput(attrs={'class': 'form-control'}), required=False)
    ano = forms.ChoiceField(label='Data da Publicação', choices=ANO_CHOICES,
                            widget=forms.Select(attrs={'class': 'form-control'}))
    co_autores = forms.ModelMultipleChoiceField(queryset=Associados.objects.all(), required=False,
                                                widget=forms.SelectMultiple(attrs={'class': 'form-control'}))
    arquivo = forms.FileField(label='Selecione um arquivo',
                              widget=forms.FileInput(attrs={'accept': 'application/pdf'}))

publicacoes/views.py
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.shortcuts import render
from .models import Publicacoes
from publicacoes.forms import PublicacoesForm


@login_required
def submeter_publicacao(request):
    if request.method == 'POST':
        form = PublicacoesForm(request.POST, request.FILES)
        if form.is_valid():
            public_model = Publicacoes()
            public_model.titulo = form.cleaned_data['titulo']
            public_model.tipo_publicacao = form.cleaned_data['tipo_publicacao']
            public_model.tipo_artigo = form.cleaned_data['tipo_artigo']
            public_model.nome_evento = form.cleaned_data['nome_evento']
            public_model.local_evento = form.cleaned_data['local_evento']
            public_model.ano = form.cleaned_data['ano']
            public_model.arquivo = request.FILES['arquivo']
            public_model.autor_principal = request.user
            public_model.save()
            public_model.autor_secundario = form.cleaned_data['co_autores']
            public_model.save()
            form = PublicacoesForm()
            messages.success(request, "Publicação Enviada com sucesso!")
    else:
        form = PublicacoesForm()
    template = 'submit_pbc.html'
    context = {'form': form}

    return render(request, template, context)


def publicacoes(request):
    public_all = Publicacoes.objects.all()
    template_name = 'publicacoes.html'
    context = {'publicacoes': public_all}

    return render(request, template_name, context)

publicacoes/templates/publicacoes.html
{% extends "base.html" %}
{% load static %}
{% block conteudo %}
    <div class="container">
        <div class="panel panel-default">
            <div class="panel-heading">
                <div role="tabpanel">
                    <div class="panel-title">
                        <h3>
                            <span class="glyphicon glyphicon-folder-open"></span> Publicações
                            {% if user.is_authenticated %}
                                <a href="{% url 'publicacoes:submit-publicacoes' %}" class="btn btn-primary-login">
                                    Enviar Publicações
                                    <span class="glyphicon glyphicon-open" aria-hidden="true"></span>
                                </a>
                            {% endif %}
                        </h3>
                    </div>
                </div>
            </div>
        </div>

        <ul class="nav nav-tabs" role="tablist">
            <li role="presentation" class="active">
                <a href="#tcc" aria-controls="home" role="tab" data-toggle="tab">
                    Trabalhos TCC
                </a>
            </li>
            <li role="presentation">
                <a href="#periodicos" aria-controls="profile" role="tab" data-toggle="tab">
                    Periodicos
                </a>
            </li>
            <li role="presentation">
                <a href="#anaisCongresso" aria-controls="profile" role="tab" data-toggle="tab">
                    Anais de Congressos
                </a>
            </li>
        </ul>
        <div class="tab-content">
            <div role="tabpanel" class="tab-pane active" id="tcc">
                <h4>Relatórios de Conclusão</h4>
                {% for p in publicacoes %}
                    {% if p.tipo_publicacao == 0 %}
                        <div class="col-md-12">
                            {{ p.autor_principal }}.
                            <b>{{ p.titulo }}.</b>
                            {{ p.nome_evento }}.
                            {{ p.local_evento }}.
                            {{ p.ano }}.
                            <a href="{{ p.arquivo.url }}" target="_blank">
                                <span class="glyphicon glyphicon-download-alt" aria-hidden="true"></span>
                            </a>
                        </div>
                    {% endif %}
                {% endfor %}
            </div>
            <div role="tabpanel" class="tab-pane" id="periodicos">
                {% for p in publicacoes %}
                    {% if forloop.first %}
                        <h4>Artigo Completo</h4>
                    {% endif %}
                    {% if p.tipo_publicacao == 1 %}
                        {% if p.tipo_artigo == 0 %}
                            {{ p.autor_principal }}.
                            <b>{{ p.titulo }}.</b>
                            {{ p.nome_evento }}.
                            {{ p.local_evento }}.
                            {{ p.ano }}.
                            <a href="{{ p.arquivo.url }}" target="_blank">
                                <span class="glyphicon glyphicon-download-alt" aria-hidden="true"></span>
                            </a>
                        {% endif %}
                    {% endif %}
                {% endfor %}
                {% for p in publicacoes %}
                    {% if forloop.first %}
                        <h4>Resumos</h4>
                    {% endif %}
                    {% if p.tipo_publicacao == 1 %}
                        {% if p.tipo_artigo == 1 %}
                            {{ p.autor_principal }}.
                            <b>{{ p.titulo }}.</b>
                            {{ p.nome_evento }}.
                            {{ p.local_evento }}.
                            {{ p.ano }}.
                            <a href="{{ p.arquivo.url }}" target="_blank">
                                <span class="glyphicon glyphicon-download-alt" aria-hidden="true"></span>
                            </a>
                        {% endif %}
                    {% endif %}
                {% endfor %}
            </div>
            <div role="tabpanel" class="tab-pane" id="anaisCongresso">
                {% for p in publicacoes %}
                    {% if forloop.first %}
                        <h4>Artigo Completo</h4>
                    {% endif %}
                    {% if p.tipo_publicacao == 2 %}
                        {% if p.tipo_artigo == 0 %}
                            {{ p.autor_principal }}.
                            <b>{{ p.titulo }}.</b>
                            {{ p.nome_evento }}.
                            {{ p.local_evento }}.
                            {{ p.ano }}.
                            <a href="{{ p.arquivo.url }}" target="_blank">
                                <span class="glyphicon glyphicon-download-alt" aria-hidden="true"></span>
                            </a>
                        {% endif %}
                    {% endif %}
                {% endfor %}
                {% for p in publicacoes %}
                    {% if forloop.first %}
                        <h4>Resumos</h4>
                    {% endif %}
                    {% if p.tipo_publicacao == 2 %}
                        {% if p.tipo_artigo == 1 %}
                            {{ p.autor_principal }}.
                            <b>{{ p.titulo }}.</b>
                            {{ p.nome_evento }}.
                            {{ p.local_evento }}.
                            {{ p.ano }}.
                            <a href="{{ p.arquivo.url }}" target="_blank">
                                <span class="glyphicon glyphicon-download-alt" aria-hidden="true"></span>
                            </a>
                        {% endif %}
                    {% endif %}
                {% endfor %}
            </div>
        </div>
    </div>
{% endblock %}

publicacoes/templates/submit_pbc.html
{% extends 'base.html' %}
{% block conteudo %}
    <div class="container">
        {% if messages %}
            <div class="alert alert-success alert-dismissible" role="alert">
                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
                {% for message in messages %}
                    {{ message }} <a href="{% url 'publicacoes:publicacoes' %}" class="alert-link">Retorne para a página de publicações</a>
                {% endfor %}
            </div>
        {% endif %}
        <div class="row">
            <div class="col-lg-6 col-sm-6 col-12">
                <h4>ENVIAR PUBLICAÇÃO</h4>
                <!-- Upload form. Note enctype attribute! -->
                <form action="{% url "publicacoes:submit-publicacoes" %}" method="post" enctype="multipart/form-data">
                    {% csrf_token %}
                    <div class="form-group">
                        {% for f in form %}
                            {% if not forloop.last %}
                                {{ form.non_field_errors }}
                                {{ f.label_tag }}
                                {{ f }}
                                {{ f.errors }}
                            {% endif %} 
                        {% endfor %}
                        <br>

                        <div class="input-group">
                            <span class="input-group-btn">
                                <span class="btn btn-primary-login btn-file">
                                    {{ form.arquivo.label_tag }}{{ form.arquivo }}
                                </span>
                            </span>
                            <input type="text" class="form-control" readonly >
                        </div>
                        <p>{{ form.arquivo.errors }}</p>
                    </div>
                    <div class="form-group">
                        <input class="btn btn-primary-login" type="submit" value="Enviar" />
                    </div>
                </form>
            </div>
        </div>
    </div>
{% endblock %}