core/urls.py
from django.conf.urls import patterns, url

urlpatterns = patterns('core.views',
    url(r'^index/$', 'base', name='index'),


)

doctecnicos/urls.py
from django.conf.urls import patterns, url

urlpatterns = patterns('doctecnicos.views',
    url(r'^submeter-documentos-tecnicos/$', 'submeter_documento', name='submit-documentos-tecnicos'),
    url(r'^documentos-tecnicos/$', 'lista_documentos', name='documentos-tecnicos'),

)

site_leds/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = patterns('',
    url(r'^$', include('noticias.urls', namespace='noticias')),
    url(r'^conta/', include('contas.urls', namespace='contas')),
    url(r'^documentos-tecnicos/', include('doctecnicos.urls', namespace='doctecnicos')),
    url(r'^quem-somos/', include('membros.urls', namespace='membros')),
    # url(r'^$', include('noticias.urls', namespace='home')),
    url(r'^noticias/', include('noticias.urls', namespace='noticias')),
    url(r'^projetos/', include('projetos.urls', namespace='projetos')),
    url(r'^publicacoes/', include('publicacoes.urls', namespace='publicacoes')),
    url(r'^relatorio/', include('relatorio.urls', namespace='relatorio')),
    url(r'^quem-somos/', include('leds.urls', namespace='quemSomos')),
    url(r'^core/', include('core.urls', namespace='core')),#apagar depois

    # chamado no template base para exibir o perfil do associado ao clicar sobre o seu nome
    url(r'^quem-somos/associados/(?P<slug>[\w_-]+)/$', 'membros.views.perfil', name='perfil'),

    url(r'^redactor/', include('redactor.urls')),

    url(r'^admin/', include(admin.site.urls)),
)

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

doctecnicos/models.py
from django.db import models
from membros.models import Associados


class DocumentosTecnicos(models.Model):
    nome = models.CharField('Nome', max_length=100)
    descricao = models.TextField('Descrição', blank=True)
    arquivo = models.FileField('Arquivo', upload_to='media/pdf/%Y/%m/%d')
    propietario = models.ForeignKey(Associados, verbose_name='Propietário', related_name='proprietáio')

    created_at = models.DateTimeField('Criado em', auto_now_add=True)
    updated_at = models.DateTimeField('Atualizado em', auto_now=True)

    def __str__(self):
        return self.nome

    class Meta:
        verbose_name = 'Documento Técnico'
        verbose_name_plural = 'Documentos Técnicos'

doctecnicos/forms.py
from django import forms


class DocumentosTecForm(forms.Form):
    arquivo = forms.FileField(label='Selecione um arquivo',
                              widget=forms.FileInput(attrs={'accept': 'application/pdf'}))
    nomeDocumento = forms.CharField(label='Nome do documento', max_length=100,
                                    widget=forms.TextInput(attrs={'class': 'form-control'}))
    descricaoDocumento = forms.CharField(label='Descrição do Documento',
                                         widget=forms.Textarea(attrs={'class': 'form-control'}), required=False)

doctecnicos/views.py
from django.contrib import messages
from django.shortcuts import render
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger

from .forms import DocumentosTecForm
from .models import DocumentosTecnicos


@login_required
def submeter_documento(request):
    if request.method == 'POST':
        form = DocumentosTecForm(request.POST, request.FILES)
        if form.is_valid():
            model_doc = DocumentosTecnicos()
            model_doc.nome = form.cleaned_data['nomeDocumento']
            model_doc.descricao = form.cleaned_data['descricaoDocumento']
            model_doc.arquivo = request.FILES['arquivo']
            model_doc.propietario = request.user
            model_doc.save()
            form = DocumentosTecForm()
            messages.success(request, "Documento Enviado com sucesso!")
    else:
        form = DocumentosTecForm()
    template = 'submit_dt.html'
    context = {'form': form}

    return render(request, template, context)


def lista_documentos(request):
    documentos_list = DocumentosTecnicos.objects.all()
    paginator = Paginator(documentos_list, 10)

    page = request.GET.get('page')
    try:
        documentos = paginator.page(page)
    except PageNotAnInteger:
        documentos = paginator.page(1)
    except EmptyPage:
        documentos = paginator.page(paginator.num_pages)

    template = 'documentos_tecnicos.html'
    context = {'documentos': documentos, 'paginator': paginator}
    return render(request, template, context)

doctecnicos/templates/documentos_tecnicos.html
{% extends 'base.html' %}
{% block conteudo %}
    <div class="container marketing">
        <div class="panel panel-default">
            <div class="panel-body">
                <div class="panel-title">
                    <h3>
                        <span class="glyphicon glyphicon-folder-open" aria-hidden="true"></span> Documentos Técnicos
                        {% if user.is_authenticated %}
                            <a href="{% url 'doctecnicos:submit-documentos-tecnicos' %}" class="btn btn-primary-login">
                                Submeter Documento
                                <span class="glyphicon glyphicon-open" aria-hidden="true"></span>
                            </a>
                        {% endif %}
                    </h3>
                </div>
            </div>
        </div>

        {% for documento in documentos %}

            <div class="row featurette">
                <div class="col-md-8 col-md-offset-1">
                    <h3 class="featurette-heading-doc text-justify">{{ documento.nome }}</h3>
                    <p class="lead text-justify">{{ documento.descricao }}</p>
                </div>
                <div class="col-md-2">
                    <a href="{{ documento.arquivo.url }}" class="btn btn-primary-login btn-lg" role="button">Download
                    <span class="glyphicon glyphicon-download-alt" aria-hidden="true"></span></a>
                </div>
            </div>
            <hr class="featurette-divider"></hr>
        {% endfor %}

        <nav class="text-center">
            <ul class="pagination pagination-lg">
                {% if documentos.has_previous %}
                    <li>
                        <a href="?page={{ documentos.previous_page_number }}" aria-label="Previous">
                            <span aria-hidden="true">&laquo;</span>
                        </a>
                    </li>
                {% endif %}

                {% for pag in paginator.page_range %}
                    <li {% if pag == documentos.number %} class="active"{% endif %}>
                        <a href="?page={{ pag }}">{{ pag }}</a>
                    </li>
                {% endfor %}

                {% if documentos.has_next %}
                    <li>
                        <a href="?page={{ documentos.next_page_number }}" aria-label="Previous">
                            <span aria-hidden="true">&raquo;</span>
                        </a>
                    </li>
                {% endif %}
            </ul>
        </nav>
    </div>

{% endblock %}

doctecnicos/templates/submit_dt.html
{% extends 'base.html' %}
{% block conteudo %}
    <div class="container">
        {% if messages %}
            <div class="alert alert-success alert-dismissible" role="alert">
                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
                {% for message in messages %}
                    {{ message }} <a href="{% url 'doctecnicos:documentos-tecnicos' %}" class="alert-link">Retorne para a página de documentos</a>
                {% endfor %}
            </div>
        {% endif %}
        <div class="row">
            <div class="col-lg-6 col-sm-6 col-x">
                <h4>ENVIAR UM DOCUMENTO TÉCNICO</h4>
                <form action="{% url "doctecnicos:submit-documentos-tecnicos" %}" method="post" enctype="multipart/form-data">
                    {% csrf_token %}
                    <div class="form-group">
                        <p>{{ form.non_field_errors }}</p>
                        <p>{{ form.nomeDocumento.label_tag }}<br>{{ form.nomeDocumento }}</p>{{ form.nomeDocumento.errors }}

                        <p>{{ form.descricaoDocumento.label_tag }}<br>{{ form.descricaoDocumento }}</p>

                        <div class="input-group">
                            <span class="input-group-btn">
                                <span class="btn btn-primary-login btn-file">
                                    {{ form.arquivo.label_tag }}{{ form.arquivo }}
                                </span>
                            </span>
                            <input type="text" class="form-control" readonly>
                        </div>
                        <p>{{ form.arquivo.errors }}</p>
                    </div>
                    <div class="form-group">
                        <input class="btn btn-primary-login" type="submit" value="Enviar" />
                    </div>
                </form>
            </div>
        </div>
    </div>
{% endblock %}